### ISSUE TITLE
need larger more trustworthy ETB driver

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#16]
See https://github.com/andreika-git/hellen-one/issues/28

**Comment by rusefillc** [comment]
That's about
![image](https://user-images.githubusercontent.com/48498823/114761001-fa198e00-9d2d-11eb-8fdb-df403e1f8594.png)


Please rename network names

**Comment by rusefillc** [comment]
Let's go with L6205

**Comment by Qwerty-OFF** [comment]
Done
