### ISSUE TITLE
Test order attempt

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#24]
U103 | AP2331W-7 | SC59 | Diodes Incorporated AP2331W-7Extended PartSC-59C460346 | 1 | $0.1329 | Inventory shortage
-- | -- | -- | -- | -- | -- | --

Q300,Q301,Q302,Q303,Q304 | AO3401A | SOT-23 | No part selected
-- | -- | -- | --

U430,U430_2 | TJA1051T/3/1J | SO8 | No part selected
-- | -- | -- | --

**Comment by rusefillc** [comment]
AO3401A -> C347476
TJA1051T -> C92211

**Comment by Qwerty-OFF** [comment]
Fixed:
> AO3401A -> C347476
> TJA1051T -> C92211

we use a diode because we did not find a replacement for AP2113 on JLC
