### ISSUE TITLE
Cam and crank sniffing vias

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#25]
As of today we do not have super reliable way to record digital trigger inputs. For right now the best way to troubleshoot anything related to trigger would be hooking up an external logic ananlyzer device between cam/crank signal conditioning and MCU.

We need a via on both cam and crank MCU traces to allow soldering of a pin for external logic analyzer.

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/120904179-71dfa700-c653-11eb-9f67-389350976d80.png)
