### ISSUE TITLE
diode for vvt and idle outputs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#27]
See https://github.com/andreika-git/hellen-one/issues/40

**Comment by andreika-git** [comment]
Hellen121vag has 2 vvts. and both don't use external mosfets at all, not to speak of diodes.
The first one uses 1A double ls-outputs, the second one uses "middle-power" solenoid push-pull drivers.

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/120904238-e0246980-c653-11eb-8afa-686998e1365c.png)
