### ISSUE TITLE
connect 12v LED to 12v raw instead of 12v

### ISSUE THREAD

**Issue by mck1117** [rusefi/hellen121vag#28]
![image](https://user-images.githubusercontent.com/568254/117756420-fa913180-b1d2-11eb-9913-5852631d8b01.png)

**Comment by mck1117** [comment]
the manifestation is that the 12v LED is on while powered from USB

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/120904352-88d2c900-c654-11eb-8e32-17fb42bc2d72.png)
