### ISSUE TITLE
Put mission statement right on the board silkscreen

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#30]
Back side silk:

"Always looking for C/C++/PHP/Java developers
https://rusefi.com/s/mission"

**Comment by rusefillc** [comment]
https://github.com/rusefi/hellen154vag-9.1/issues/7

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/121819488-09697900-cc96-11eb-95d2-53f01219df5e.png)
