### ISSUE TITLE
less crazy routing for ignition outputs

### ISSUE THREAD

**Issue by mck1117** [rusefi/hellen121vag#32]
maybe put ignition driver module closer to output pins, instead of routing the ignition output signals half way around the board like this: 

![image](https://user-images.githubusercontent.com/568254/119061356-0924d900-b989-11eb-8b67-2ac5bfa044de.png)

**Comment by rusefillc** [comment]
Maybe time to 4 layer?

**Comment by mck1117** [comment]
I mean move the module.  The routing is fine, I'd just rather not have "outside world" signals making a huge loop area.  Much better to locate the potentially noisy drivers close to the plug, instead of clear across the board.

**Comment by mck1117** [comment]
poke?

**Comment by rusefillc** [comment]
We will have a bigger change with rev C while adding SD card

**Comment by rusefillc** [comment]
pictured U460 is the ignition module piece
