### ISSUE TITLE
[safety] Add pulldown to L6205 enable line

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#33]
Add a pulldown resistor to L6205 enable. If the STM32 pin floats (reset, programming, during init, etc), the ETB driver must be disabled.

Also, remove R47. No need for a series resistor.

![image](https://user-images.githubusercontent.com/48498823/120013260-861a0900-bfae-11eb-8150-4652a990d0e8.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/120905010-f46a6580-c657-11eb-9b11-e776aa5ef55c.png)
