### ISSUE TITLE
Document R2 R3 R8 R9

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#35]
Please document https://github.com/rusefi/rusefi/wiki/Hellen121VAG#vehicle-specific-jumpers since we had a bit of first turn-on drama

**Comment by rusefillc** [comment]
@Qwerty-OFF please review https://github.com/rusefi/rusefi/wiki/Hellen121VAG#vehicle-specific-jumpers

**Comment by Qwerty-OFF** [comment]
Looks nice
In revision b, dangerous jumpers have been removed from the BOM
![image](https://user-images.githubusercontent.com/4116383/120905136-b3268580-c658-11eb-89ba-1d2cc420a32c.png)
