### ISSUE TITLE
Please add words

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#37]
![image](https://user-images.githubusercontent.com/48498823/120889339-93e11700-c5ca-11eb-8779-e2f445a85b43.png)

PUMP -> Fuel Pump Relay
MAIN -> Main Relay
CE -> Radiator Fan
OUT_CE -> OUT_RADIATOR_FAN

Open question if we need a unified language for many Hellen or if we shall use the naming convention of the specific vehicle or both

**Comment by rusefillc** [comment]
@andreika-git says that CE is check engine

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/120905466-e36f2380-c65a-11eb-8c86-07b63716961a.png)
