### ISSUE TITLE
Remove Q313 from rev A pieces

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#39]
From power supply of all five boards we need to remove Q301 same as 

![image](https://user-images.githubusercontent.com/48498823/121229897-893db080-c85c-11eb-99b6-2e93bd5b8374.png)

@kon please mod your board

**Comment by rusefillc** [comment]
@mck1117 please mod the board in your possession

**Comment by mck1117** [comment]
done

**Comment by Qwerty-OFF** [comment]
Fixed in output-0.2
