### ISSUE TITLE
Document F1/F2

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#40]
F1/F2 seems to be similar to R2 R3 R8 R9

I think we shall document R2/R3/R8/R9 meaning with a bit of text right on PCB?

**Comment by rusefillc** [comment]
also open question of we can put any relevant text right on the PCB or not even bother?

@Qwerty-OFF maybe F1 can say "from 121" and F2 can say "from blah blah" etc? R2 could say "MR to 21"?

**Comment by andreika-git** [comment]
First attempt to add F1/F2 jumpers to the H121vag wiki page:
![image](https://user-images.githubusercontent.com/15104768/121322098-57d5eb00-c917-11eb-9f06-bbfadb1ed1ee.png)

**Comment by Qwerty-OFF** [comment]
We can do something like this if we need and have enogh space on the board
![image](https://user-images.githubusercontent.com/4116383/121417533-af557480-c972-11eb-95bc-8ba572abb0b6.png)

**Comment by rusefillc** [comment]
Looks great!
