### ISSUE TITLE
Trying to fab rev B

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#46]
less expected
![image](https://user-images.githubusercontent.com/48498823/121937109-568e2f00-cd18-11eb-9444-b8c4eacd28d2.png)

expected
![image](https://user-images.githubusercontent.com/48498823/121937147-5ee66a00-cd18-11eb-9ccf-c8c31cbbbf83.png)

**Comment by mck1117** [comment]
bts3028 is expected, that's the wbo mosfet that I was already going to get

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/121958053-34ed7180-cd31-11eb-80e0-3b6aed5b1c97.png)

**Comment by rusefillc** [comment]
^^^ my bad, sorry
