### ISSUE TITLE
Connect J1-6 USB cable shield to GND

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#62]
J1-6 USB cable shield was not connected to GND due to tracing issues with JLC tolerances.

We should connect J1-6 USB cable shield to GND once we migrate board to 4 layers

**Comment by mck1117** [comment]
...how was this a problem with JLC tolerance?

The recommendation is not shorting the shield to ground.  On proteus it has a 100n + 100k in parallel to ground.

**Comment by mck1117** [comment]
ok looks like there are conflicting opinions in the literature about what's best - let's put an 0603 pad for now with a 0 ohm mounted

**Comment by hasl58** [comment]
>>in the literature

link please show

**Comment by mck1117** [comment]
https://electronics.stackexchange.com/a/4519

**Comment by hasl58** [comment]
if USB 2.0 and less pin6 to GND
if USB 3.0 and large pin6 from resistor

**Comment by hasl58** [comment]
ok. i connect through resistor.

**Comment by rusefillc** [comment]
@hasl58 what exact lib file would need to be changed? is that some standard library or rusEFI custom library https://github.com/rusefi/kicad-libraries/ ?

if it's https://github.com/rusefi/kicad-libraries/ we would need a pull request into https://github.com/rusefi/kicad-libraries/ - i.e. fork https://github.com/rusefi/kicad-libraries/ and etc same process as PR into this hellen121vag here
