### ISSUE TITLE
ETB simplify manual soldering

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#74]
@Qwerty-OFF can we move C1 and C2 1mm away from huge chip to simplify hand-soldering, as long as trivial level of effort?

![image](https://user-images.githubusercontent.com/48498823/136836814-1fc16866-04cc-4351-84e6-7e6c5c7952a9.png)

**Comment by hasl58** [comment]
may be one tantal capasitor 100uF

**Comment by hasl58** [comment]
and one 100nF

**Comment by hasl58** [comment]
![20211011213325](https://user-images.githubusercontent.com/17414812/136837916-f2434b0b-3dcc-4e54-897c-095a2e1a9164.jpg)

or so
