### ISSUE TITLE
Jumpers table for 2004 3.2

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#77]
Please fill in https://github.com/rusefi/rusefi/wiki/Hellen121VAG#vehicle-specific-jumpers for https://github.com/rusefi/rusefi/wiki/2004-Cayenne

**Comment by Qwerty-OFF** [comment]
Updated
Please check that this is 12V_IGN powered by key
![image](https://user-images.githubusercontent.com/4116383/139596502-412a11e2-2125-4a27-a2c6-769de0cb0167.png)

**Comment by NMSTEC** [comment]
Confirmed this is IGN/Terminal 15 from kessy to ECU & other modules.
![DIN VAG](https://user-images.githubusercontent.com/45252464/139599519-440a424c-5f6e-4820-8eb4-d938e27b8680.png)
