### ISSUE TITLE
Schematics usability: explicit VR_THRESHOLD net name on other end

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#78]
let's explicitly label E18 net on this part of schematics

![image](https://user-images.githubusercontent.com/48498823/139600323-698bfb28-12ca-4c3e-a984-3dd8d6db7fff.png)

**Comment by Qwerty-OFF** [comment]
Fixed
![image](https://user-images.githubusercontent.com/4116383/195919934-c2daf1df-5d80-4088-9e36-ff0b4a5ddc5a.png)
