### ISSUE TITLE
Evaluate KiCAD 7

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121vag#89]
What does KiCAD 7 mean for us?

Can we please "convert" this board just as an example into KiCAD 7 if there is such thing as KiCAD7? Let's go as far as export artifacts and try the complete hellen workflow on those new artifacts

**Comment by chuckwagoncomputing** [comment]
I'm keeping an eye on Kicad 7. Looks like I don't have the ability to assign this to myself.

**Comment by chuckwagoncomputing** [comment]
When I open this board with Kicad 7, I get some components off the side of the board.
Could someone confirm whether this is the case with older versions?
![image](https://user-images.githubusercontent.com/1531127/225188989-b6619976-20a4-4e6a-b13b-05e6654ec489.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-4chan already uses kicad7
